dataFolder: ./data
httpPort: 4000

language: en
timeZone: UTC

animation: full

modules:
  home:
    widgets:
      - clock
      - react-demo
      - svelte-demo
      # - clock
  traffic:
    apiKey: AIzaSyCMRGe3tisQkblfDg8yJ-OwSCDV_2uRq2U
    center:
      lat: 47.3915446
      long: 19.0125942
    zoom: 13

home:
  module: home
  backTimeSec: 10

sleep:
  enabled: true
  from: 23
  to: 6
