httpPort: 4000
ssl: false

dataFolder: ./data
dbFolder: db

language: en
timeZone: UTC

animation: full

homePage:
  page: home
  idleTime: 20

screenSaver:
  enabled: true
  page: slideshow
  time: 60

sleep:
  enabled: true
  from: 22
  to: 6

modules:
  home:
    widgets:
      - clock
      - weather
      - events
      - tasks
    
  ui-clock: {}

  slideshow: 
    delay: 30
    imageSize: cover
    overlayLevel: 2

  openweathermap: 
    enabled: true
    apiKey:
    location: London
    unit: metric

  flickr: {}

  ui-weather:
    enabled: true
