httpPort: 4000
ssl: false

dataFolder: ./data
dbFolder: db

language: en
timeZone: UTC

animation: full

homePage:
  page: home
  idleTime: 20

screenSaver:
  enabled: false
  page: slideshow
  time: 60

sleep:
  enabled: true
  from: 23
  to: 6

modules:
  home:
    widgets:
      - clock
      - weather
      - events
      - tasks
    
  clock: {}

  slideshow: 
    delay: 30
    imageSize: cover
