dataFolder: ./data
httpPort: 4000

language: en
timeZone: UTC

animation: full

modules:
  home:
    widgets:
      - clock
      - weather
      - events
      - tasks
    
homePage:
  module: home
  idleTime: 10

screenSaver:
  module: slideshow
  idleTime: 30

sleep:
  enabled: true
  from: 23
  to: 6
