dataFolder: ./data
httpPort: 4000

language: en
timeZone: UTC

animation: full

homePage:
  page: home
  idleTime: 10

screenSaver:
  enabled: false
  page: slideshow
  time: 30

sleep:
  enabled: true
  from: 23
  to: 6

modules:
  home:
    widgets:
      - clock
      - weather
      - events
      - tasks
    
  clock: {}

  slideshow: 
    delay: 10
    imageSize: cover
